name: Slack Bot Reporter
description: Reports job results to Slack via a Slack bot.
inputs:
  channel-id:
    required: true
  title:
    required: true
  job-status:
    required: false
runs:
  using: "composite"
  steps:
    - name: Set Slack Color for Job Status
      if: ${{ inputs.job-status != '' }}
      uses: haya14busa/action-cond@v1.0.0
      id: slack-color
      with:
        cond: ${{ inputs.job-status == 'success' }}
        if_true: "#36a64f"
        if_false: "#c91616"
    - name: Set Status Link for Job Status
      if: ${{ inputs.job-status != '' }}
      env:
        BUILD_URL: "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ inputs.job-status }}>"
    - name: Slack Notify
      if: always()
      uses: slackapi/slack-github-action@v1.19.0
      with:
        channel-id: ${{ inputs.channel-id }}
        payload: |
          {
            "attachments": [
              {
                "color": "${{ steps.slack-color.outputs.value }}",
                "blocks": [
                  {
                    "type": "header",
                    "text": {
                      "type": "plain_text",
                      "text": ${{ inputs.title }},
                      "emoji": true
                    }
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": Repo: "${{ github.event.repository.name }} Branch: ${{ github.ref_name }}"
                    }
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "${{ env.BUILD_URL }}"
                    }
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ env.SLACK_BOT_TOKEN }}
